name: "ddrv"

version: '3.8'

services:
  postgres:
    container_name: ddrvpg
    image: postgres:alpine
    volumes:
      - ddrvpg:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: ddrv
      POSTGRES_DB: ddrv
      POSTGRES_PASSWORD: ddrv
volumes:
  ddrvpg: